branches:
  only:
    - master

language: node_js
node_js:
  - 12.10.0

services:
  - postgresql

before_script:
  - psql -c "create user unatart with encrypted password 'unatart';"
  - psql -c "create database test_micro_services;"
  - psql test_micro_services -c "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";"
  - psql -c "grant all privileges on database test_micro_services to unatart;"
  - psql test_micro_services -U unatart -c "CREATE SCHEMA \"user\";"
  - psql test_micro_services -U unatart -c "CREATE SCHEMA \"story\";"
  - psql test_micro_services -U unatart -c "CREATE SCHEMA \"fav\";"
  - psql test_micro_services -U unatart -c "CREATE SCHEMA \"notify\";"
  # - psql test_micro_services -c "grant all privileges on all tables in schema \"user\" to unatart;"
  # - psql test_micro_services -c "grant all privileges on all sequences in schema \"user\" to unatart;"
  # - psql test_micro_services -c "grant all privileges on all tables in schema \"story\" to unatart;"
  # - psql test_micro_services -c "grant all privileges on all tables in schema \"fav\" to unatart;"
  # - psql test_micro_services -c "grant all privileges on all tables in schema \"notify\" to unatart;"

install:
  - npm i

script:
  - npm run build
  - npm run coverage

notifications:
  email: false

