branches:
  only:
    - master

language: node_js
node_js:
  - 12.10.0

services:
  - postgresql

before_script:
  - psql -c "create database test_micro_services;" -U postgres
  - psql -c "create user unatart with encrypted password 'unatart';" -U postgres
  - psql -c "grant all privileges on database test_micro_services to unatart;" -U postgres

install:
  - npm i

script:
  - npm run build
  - npm run coverage

notifications:
  email: false

